"""Renders docs/trade_spec.md from the code (stages, variables, edge cases), so the specification cannot drift from it.

scripts/gen_spec.py writes the file; tests/trade/test_spec.py fails when the committed file is stale.
"""
from __future__ import annotations

from app.trade import calc, edge_cases, variables


def _table(headers: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines += ["| " + " | ".join(str(c).replace("|", "/") for c in r) + " |" for r in rows]
    return "\n".join(lines)


def render_spec() -> str:
    out = [
        "# Trade calculation specification",
        "",
        "Generated by `backend/scripts/gen_spec.py` from `app/trade/calc.py`, `variables.py` and `edge_cases.py`; do not edit by hand.",
        "The only calculation lives in `backend/app/trade/calc.py` (version " + calc.CALC_VERSION + "). Research tasks: `docs/research/`.",
        "",
        "## Pipeline stages",
        "",
        "Each stage can be verified alone (from the save's recorded upstream values) and end to end (`calc.calculate`).",
        "",
        _table(["stage", "what it computes", "research"], [[n, d, ", ".join(r)] for n, (d, r) in calc.STAGE_INFO.items()]),
        "",
        "## Variables",
        "",
        "kind: constant (game files), read (save input), observed (save input, not derived yet), recorded (game result, verification only), ignored, unknown.",
        "",
        _table(["id", "kind", "save path", "stages", "research", "meaning"],
               [[v.id, v.kind, v.save_path, ", ".join(v.stages), ", ".join(v.research), v.description] for v in variables.VARIABLES]),
        "",
        "## Edge cases",
        "",
        "Every case must be exhibited by at least one fixture save (intervention cases: by an intervention-pair fixture), or be listed as known uncovered in `tests/trade/expected.py`. `absent` cases must never occur.",
        "",
        _table(["id", "level", "case", "description", "research", "must be absent"],
               [[c.id, c.level, c.title, c.description, ", ".join(c.research), "yes" if c.expect_absent else ""] for c in edge_cases.CASES]),
        "",
    ]
    return "\n".join(out)
