/// Geometry of the EU4 world as generated by `backend/scripts/build_map.py`
/// (asset `assets/map/world_map.json`): one region per trade node, the land
/// outline, and every trade route's control points. Coordinates are map pixels,
/// y pointing down.
library;

import 'dart:convert';
import 'dart:math' as math;
import 'dart:ui';

import 'package:flutter/services.dart' show rootBundle;

class MapRegion {
  final String id;
  final Offset anchor;
  final Rect bbox;
  final double area;
  final double landFraction;
  final Path path;
  final List<List<Offset>> rings;

  MapRegion({
    required this.id,
    required this.anchor,
    required this.bbox,
    required this.area,
    required this.landFraction,
    required this.path,
    required this.rings,
  });

  bool get isSea => landFraction < 0.5;

  bool contains(Offset p) => bbox.contains(p) && path.contains(p);
}

class MapRoute {
  final String from;
  final String to;
  final List<Offset> points;

  /// Smooth curve through the control points (map space).
  final Path path;
  final double length;
  late final PathMetric metric = path.computeMetrics().first;

  MapRoute({required this.from, required this.to, required this.points, required this.path, required this.length});

  String get key => '$from>$to';
}

class WorldMapData {
  final double width;
  final double height;
  final Path land;
  final Map<String, MapRegion> regions;
  final List<MapRoute> routes;
  final Map<String, MapRoute> routeByKey;

  WorldMapData({
    required this.width,
    required this.height,
    required this.land,
    required this.regions,
    required this.routes,
  }) : routeByKey = {for (final r in routes) r.key: r};

  Rect get bounds => Rect.fromLTWH(0, 0, width, height);

  /// Topmost region containing [p] (map space). Land-heavy small regions win
  /// over big sea regions when they overlap (they never should, but bbox
  /// pre-checks make the order deterministic).
  MapRegion? regionAt(Offset p) {
    MapRegion? best;
    for (final r in regions.values) {
      if (r.contains(p) && (best == null || r.area < best.area)) best = r;
    }
    return best;
  }

  static Future<WorldMapData> load() async {
    final text = await rootBundle.loadString('assets/map/world_map.json');
    return WorldMapData.parse(jsonDecode(text) as Map<String, dynamic>);
  }

  static WorldMapData parse(Map<String, dynamic> j) {
    final land = Path()..fillType = PathFillType.evenOdd;
    for (final ring in j['land'] as List) {
      _addRing(land, _points(ring as List));
    }

    final regions = <String, MapRegion>{};
    (j['nodes'] as Map<String, dynamic>).forEach((id, v) {
      final n = v as Map<String, dynamic>;
      final path = Path()..fillType = PathFillType.evenOdd;
      final rings = <List<Offset>>[];
      for (final ring in n['rings'] as List) {
        final pts = _points(ring as List);
        rings.add(pts);
        _addRing(path, pts);
      }
      final bb = (n['bbox'] as List).map((e) => (e as num).toDouble()).toList();
      final a = (n['anchor'] as List).map((e) => (e as num).toDouble()).toList();
      regions[id] = MapRegion(
        id: id,
        anchor: Offset(a[0], a[1]),
        bbox: Rect.fromLTRB(bb[0], bb[1], bb[2], bb[3]),
        area: (n['area'] as num).toDouble(),
        landFraction: (n['land_fraction'] as num?)?.toDouble() ?? 0,
        path: path,
        rings: rings,
      );
    });

    final routes = <MapRoute>[];
    for (final r in j['routes'] as List) {
      final pts = _points(r['points'] as List);
      if (pts.length < 2) continue;
      final w = (j['width'] as num).toDouble();
      // Routes that cross the Pacific seam have x outside the map; draw them
      // twice, shifted, so they are visible from either edge of the world.
      final wraps = pts.any((p) => p.dx < 0 || p.dx > w);
      final variants = <List<Offset>>[pts];
      if (wraps) {
        final shift = pts.first.dx > w / 2 || pts.last.dx > w ? -w : w;
        variants.add([for (final p in pts) Offset(p.dx + shift, p.dy)]);
      }
      for (final v in variants) {
        final path = _smoothOpen(v);
        final metrics = path.computeMetrics().toList();
        if (metrics.isEmpty) continue;
        routes.add(MapRoute(
          from: r['from'],
          to: r['to'],
          points: v,
          path: path,
          length: metrics.fold<double>(0, (a, m) => a + m.length),
        ));
      }
    }

    return WorldMapData(
      width: (j['width'] as num).toDouble(),
      height: (j['height'] as num).toDouble(),
      land: land,
      regions: regions,
      routes: routes,
    );
  }

  static List<Offset> _points(List flat) {
    final out = <Offset>[];
    for (var i = 0; i + 1 < flat.length; i += 2) {
      out.add(Offset((flat[i] as num).toDouble(), (flat[i + 1] as num).toDouble()));
    }
    return out;
  }

  /// Closed ring, corners rounded with the midpoint-quadratic trick so the
  /// stair-stepped province edges read as soft coastlines.
  static void _addRing(Path path, List<Offset> p) {
    final n = p.length;
    if (n < 3) return;
    Offset mid(int a, int b) => Offset((p[a % n].dx + p[b % n].dx) / 2, (p[a % n].dy + p[b % n].dy) / 2);
    final start = mid(0, 1);
    path.moveTo(start.dx, start.dy);
    for (var i = 1; i <= n; i++) {
      final c = p[i % n];
      final m = mid(i, i + 1);
      path.quadraticBezierTo(c.dx, c.dy, m.dx, m.dy);
    }
    path.close();
  }

  /// Open polyline through [p] rendered as a smooth curve (Catmull-Rom ->
  /// cubic Bezier), passing through every control point.
  static Path _smoothOpen(List<Offset> p) {
    final path = Path()..moveTo(p.first.dx, p.first.dy);
    if (p.length == 2) {
      path.lineTo(p.last.dx, p.last.dy);
      return path;
    }
    for (var i = 0; i < p.length - 1; i++) {
      final p0 = p[math.max(i - 1, 0)];
      final p1 = p[i];
      final p2 = p[i + 1];
      final p3 = p[math.min(i + 2, p.length - 1)];
      final c1 = p1 + (p2 - p0) / 6;
      final c2 = p2 - (p3 - p1) / 6;
      path.cubicTo(c1.dx, c1.dy, c2.dx, c2.dy, p2.dx, p2.dy);
    }
    return path;
  }
}
